version: '3'
services:
  traefik:
    image: traefik:v2.3
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--accesslog"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  ws:
    build: "./ws-app"
    environment:
      REDIS_HOST: redis
      TICKET_TTL: 180000
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ws.rule=Headers(`Upgrade`, `websocket`)"
      - "traefik.http.routers.ws.entrypoints=web"
  http:
    build: "./proxy-app"
    environment:
      REDIS_HOST: redis
      TARGET_URL: https://grid-host
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http.rule=PathPrefix(`/wd/hub`)"
      - "traefik.http.routers.http.entrypoints=web"